<?php
/*
Plugin Name:  Image Optimizer for Google Lighthouse
Text Domain:  image-optimizer-for-google-lighthouse
Description:  Upload a JSON file generated by Google's Lighthouse website auditing tool and this plugin will compress and replace all flagged images using the reSmush.it API.
Version:      1.0
Author:       Evan Norton
Author URI:   https://github.com/evannorton
License:      GPL2
License URI:  https://www.gnu.org/licenses/gpl-2.0.html

Image Optimizer for Google Lighthouse is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
any later version.

Image Optimizer for Google Lighthouse is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Image Optimizer for Google Lighthouse. If not, see https://www.gnu.org/licenses/gpl-2.0.html.

 */

function iofgl_page()
{
    include plugin_dir_path(__FILE__) . "page.php";
}

function iofgl_menu()
{
    add_media_page("Image Optimizer for Google Lighthouse", "Image Optimizer for Google Lighthouse", "administrator", "image-optimizer-for-google-lighthouse", "iofgl_page");
}

add_action("admin_menu", "iofgl_menu");
