<?php
/*
Plugin Name: Lighthouse Image Optimizer
Text Domain:  lighthouse-image-optimizer
Description:  Upload a JSON file generated by Google's Lighthouse website auditing tool and this plugin will compress and replace all flagged images using the reSmush.it API.
Version:      1.0
Author:       Evan Norton
Author URI:   https://developer.wordpress.org/
License:      GPL2
License URI:  https://www.gnu.org/licenses/gpl-2.0.html


Lighthouse Image Optimizer is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
any later version.

Lighthouse Image Optimizer is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Lighthouse Image Optimizer. If not, see https://www.gnu.org/licenses/gpl-2.0.html.

*/

function lio_page() {
    include( plugin_dir_path( __FILE__ ) . "page.php");
}

function lio_menu() {
    add_media_page("Lighthouse Image Optimizer", "Lighthouse Image Optimizer", "administrator", "lighthouse-image-Optimizer", "lio_page");
}

add_action("admin_menu", "lio_menu");